Importing libraries

In [2]:
import numpy as  np
import pandas as pd

Createing DataFrame

In [4]:
# using lists
student_data  = [
    [100,60,10],
    [50,70,7],
    [120,100,14],
    [80,50,2]
]

pd.DataFrame(student_data,columns=['iq','marks','packages'])

    iq  marks  packages
0  100     60        10
1   50     70         7
2  120    100        14
3   80     50         2

In [5]:
# using dictionary
student_dict  = {
    'iq':[100,50,120,80],
    'marks':[60,70,100,50],
    'packages':[10,7,14,2]
}
pd.DataFrame(student_dict)

    iq  marks  packages
0  100     60        10
1   50     70         7
2  120    100        14
3   80     50         2